import { logger } from '../utils/logger.js';

export interface TargetColumn {
  name: string;
  deltaType: string;
  nullable: boolean;
  isPrimaryKey?: boolean;
  comment?: string;
}

export interface TargetTable {
  catalog?: string;
  schema: string;
  name: string;
  layer: 'bronze' | 'silver' | 'gold';
  columns: TargetColumn[];
  partitionBy?: string;
  enableCdf?: boolean;
  comment?: string;
}

const AUDIT_COLUMNS: TargetColumn[] = [
  { name: '_migration_id',  deltaType: 'STRING',    nullable: false, comment: 'Migration run identifier' },
  { name: '_migrated_at',   deltaType: 'TIMESTAMP', nullable: false, comment: 'Row ingestion timestamp' },
  { name: '_source_system', deltaType: 'STRING',    nullable: false, comment: 'Source system identifier' },
  { name: '_layer',         deltaType: 'STRING',    nullable: false, comment: 'Medallion layer (bronze|silver|gold)' },
];

// Source type → Delta Lake type mapping
const TYPE_MAP: Record<string, string> = {
  // SQL Server
  int: 'INT', bigint: 'BIGINT', smallint: 'SMALLINT', tinyint: 'TINYINT',
  bit: 'BOOLEAN', float: 'DOUBLE', real: 'FLOAT',
  decimal: 'DECIMAL(18,2)', numeric: 'DECIMAL(18,2)',
  varchar: 'STRING', nvarchar: 'STRING', char: 'STRING', nchar: 'STRING', text: 'STRING', ntext: 'STRING',
  uniqueidentifier: 'STRING',
  datetime: 'TIMESTAMP', datetime2: 'TIMESTAMP', date: 'DATE', time: 'STRING', smalldatetime: 'TIMESTAMP',
  // PostgreSQL
  integer: 'INT', int4: 'INT', int8: 'BIGINT', int2: 'SMALLINT',
  boolean: 'BOOLEAN', bool: 'BOOLEAN',
  double_precision: 'DOUBLE',
  timestamp: 'TIMESTAMP', timestamptz: 'TIMESTAMP',
  uuid: 'STRING', jsonb: 'STRING', json: 'STRING', xml: 'STRING',
  // MySQL
  tinyint_1: 'BOOLEAN', mediumint: 'INT',
  longtext: 'STRING', mediumtext: 'STRING', tinytext: 'STRING',
  datetime_mysql: 'TIMESTAMP',
};

export class DdlGenerator {
  mapType(sourceType: string, precision?: number, scale?: number): string {
    const base = sourceType.toLowerCase().replace(/\s+/g, '_').replace(/\(.*\)/, '');
    const mapped = TYPE_MAP[base] ?? 'STRING';

    if (mapped.startsWith('DECIMAL') && precision != null && scale != null) {
      return `DECIMAL(${precision},${scale})`;
    }
    return mapped;
  }

  generateCreateTable(table: TargetTable, platform: 'databricks' | 'fabric' = 'databricks'): string {
    const allColumns = [...table.columns, ...AUDIT_COLUMNS];
    const columnDefs = allColumns
      .map(col => {
        const nullable = col.nullable ? '' : ' NOT NULL';
        const comment = col.comment ? ` COMMENT '${col.comment}'` : '';
        return `  ${col.name.padEnd(24)} ${col.deltaType}${nullable}${comment}`;
      })
      .join(',\n');

    const qualifiedName = table.catalog
      ? `${table.catalog}.${table.schema}.${table.name}`
      : `${table.schema}.${table.name}`;

    const partitionClause = table.partitionBy
      ? `PARTITIONED BY (DATE(${table.partitionBy}))`
      : layer_default_partition(table.layer);

    const cdfProp = table.enableCdf !== false
      ? `  'delta.enableChangeDataFeed' = 'true'`
      : '';

    const tableComment = table.comment ?? `${table.layer} layer — auto-generated by ddl-generator`;

    const fabricNote = platform === 'fabric'
      ? '-- Microsoft Fabric: use CREATE TABLE in Warehouse or CREATE EXTERNAL TABLE in Lakehouse\n'
      : '';

    return `${fabricNote}-- Auto-generated DDL | layer: ${table.layer}
CREATE TABLE IF NOT EXISTS ${qualifiedName} (
${columnDefs}
)
USING DELTA
${partitionClause}
TBLPROPERTIES (
${cdfProp}
)
COMMENT '${tableComment}';`;
  }

  generateDropTable(table: TargetTable): string {
    const qualifiedName = table.catalog
      ? `${table.catalog}.${table.schema}.${table.name}`
      : `${table.schema}.${table.name}`;
    return `DROP TABLE IF EXISTS ${qualifiedName};`;
  }

  generateAll(tables: TargetTable[], platform: 'databricks' | 'fabric' = 'databricks'): string {
    logger.info(`Generating DDL for ${tables.length} tables on ${platform}`);
    return tables.map(t => this.generateCreateTable(t, platform)).join('\n\n');
  }
}

function layer_default_partition(layer: 'bronze' | 'silver' | 'gold'): string {
  if (layer === 'bronze') return 'PARTITIONED BY (DATE(_migrated_at))';
  if (layer === 'silver') return 'PARTITIONED BY (DATE(_migrated_at))';
  return ''; // gold tables typically not partitioned by ingestion date
}
