import { logger } from '../utils/logger.js';

export interface ColumnMapping {
  source: string;
  target: string;
  sourceType: string;
  targetType: string;
  operation: 'map' | 'rename' | 'mask' | 'tokenize' | 'pseudonymize' | 'encrypt' | 'derive' | 'drop';
  emptyStringToNull?: boolean;
  maskPattern?: string;
  derivedExpression?: string;
  pii?: string;
}

export interface TableMapping {
  sourceSchema: string;
  sourceTable: string;
  targetSchema: string;
  targetTable: string;
  strategy: 'full' | 'incremental';
  watermarkColumn?: string;
  columns: ColumnMapping[];
}

export interface EtlScript {
  table: string;
  layer: 'bronze' | 'silver' | 'gold';
  sql: string;
  language: 'sql' | 'pyspark';
}

const PII_MASKING_UDFS: Record<string, string> = {
  mask_email: `CREATE OR REPLACE FUNCTION mask_email(email STRING) RETURNS STRING
RETURN CASE
  WHEN email IS NULL THEN NULL
  WHEN LOCATE('@', email) > 0
    THEN CONCAT(SUBSTRING(email, 1, 1), '***@', SUBSTRING_INDEX(email, '@', -1))
  ELSE '***'
END;`,
  tokenize_cpf: `CREATE OR REPLACE FUNCTION tokenize_cpf(cpf STRING) RETURNS STRING
RETURN SHA2(CONCAT('cpf-salt-2024', REGEXP_REPLACE(cpf, '[^0-9]', '')), 256);`,
  pseudonymize_name: `CREATE OR REPLACE FUNCTION pseudonymize_name(name STRING) RETURNS STRING
RETURN CONCAT('Person-', SUBSTRING(SHA2(name, 256), 1, 8));`,
  mask_phone: `CREATE OR REPLACE FUNCTION mask_phone(phone STRING) RETURNS STRING
RETURN CASE WHEN phone IS NULL THEN NULL ELSE CONCAT(SUBSTRING(phone, 1, 4), '****', SUBSTRING(phone, -2)) END;`,
};

export class EtlGenerator {
  generateBronzeSql(mapping: TableMapping, migrationId: string): EtlScript {
    const cols = mapping.columns
      .filter(c => c.operation !== 'drop')
      .map(c => this.renderBronzeColumn(c))
      .join(',\n    ');

    const watermarkFilter = mapping.strategy === 'incremental' && mapping.watermarkColumn
      ? `WHERE ${mapping.watermarkColumn} > '\${last_watermark}'`
      : '';

    const sql = `-- Auto-generated by etl-generator | mappingId: ${migrationId}
-- ${mapping.sourceSchema}.${mapping.sourceTable} → ${mapping.targetSchema}.${mapping.targetTable} (bronze)
-- DO NOT EDIT — regenerate from mapping manifest

INSERT INTO ${mapping.targetSchema}.${mapping.targetTable}
SELECT
    ${cols},
    '${migrationId}'        AS _migration_id,
    CURRENT_TIMESTAMP()     AS _migrated_at,
    '${mapping.sourceSchema}.${mapping.sourceTable}' AS _source_system,
    'bronze'                AS _layer
FROM source.${mapping.sourceSchema}_${mapping.sourceTable}
${watermarkFilter};`;

    logger.debug(`Generated bronze SQL for ${mapping.sourceTable}`);
    return { table: mapping.sourceTable, layer: 'bronze', sql, language: 'sql' };
  }

  generateSilverSql(mapping: TableMapping, migrationId: string): EtlScript {
    const cols = mapping.columns
      .filter(c => c.operation !== 'drop')
      .map(c => this.renderSilverColumn(c))
      .join(',\n    ');

    const sql = `-- Auto-generated by etl-generator | mappingId: ${migrationId}
-- bronze.${mapping.targetTable} → silver.${mapping.targetTable}
-- PII masked in this layer

INSERT INTO silver.${mapping.targetTable}
SELECT
    ${cols},
    _migration_id,
    _migrated_at,
    _source_system,
    'silver' AS _layer
FROM ${mapping.targetSchema}.${mapping.targetTable};`;

    return { table: mapping.sourceTable, layer: 'silver', sql, language: 'sql' };
  }

  generateMaskingFunctions(): string {
    return Object.values(PII_MASKING_UDFS).join('\n\n');
  }

  generateRollbackSql(tables: string[], schemas: string[]): string {
    const drops = schemas.flatMap(schema =>
      tables.map(t => `DROP TABLE IF EXISTS ${schema}.${t};`),
    );
    return `-- Rollback DDL — auto-generated\n-- Run ONLY if migration must be aborted\n\n${drops.join('\n')}`;
  }

  private renderBronzeColumn(col: ColumnMapping): string {
    if (col.emptyStringToNull) {
      return `CASE WHEN ${col.source} = '' THEN NULL ELSE ${col.source} END AS ${col.target}  -- empty→NULL`;
    }
    if (col.source !== col.target) {
      return `${col.source} AS ${col.target}`;
    }
    if (col.pii) {
      return `${col.source}  -- PII: ${col.pii} (kept raw in bronze)`;
    }
    return col.source;
  }

  private renderSilverColumn(col: ColumnMapping): string {
    switch (col.operation) {
      case 'mask':
        return `mask_email(${col.source}) AS ${col.target}  -- masked`;
      case 'tokenize':
        return `tokenize_cpf(${col.source}) AS ${col.target}  -- tokenized`;
      case 'pseudonymize':
        return `pseudonymize_name(${col.source}) AS ${col.target}  -- pseudonymized`;
      case 'encrypt':
        return `AES_ENCRYPT(${col.source}, '\${ENCRYPTION_KEY}') AS ${col.target}  -- encrypted`;
      case 'derive':
        return `(${col.derivedExpression}) AS ${col.target}`;
      default:
        return col.source !== col.target ? `${col.source} AS ${col.target}` : col.source;
    }
  }
}
